host: splunk.corp.redhat.com
username: randalap
password: Spring@03
search_host: https://api.access.redhat.com
search_type:
start_time:
end_time:
save_url: https://lightbluedatasvc.dev.a1.vary.redhat.com/
cert_path: /home/randalap/NetBeansProjects/lightblue-certs/lb-randalap.pem
passphrase: o423k3kv
save_entity_name: containerMetric
save_entity_version: 0.0.3
crane_host: https://registry.access.redhat.com
